# Workflow to build a GitHub Pages site for multiple branches simultaneously

# NOTE: to make this work, in GitHub Settings under Pages – Build and Deployment
# change Source from "Deploy from a branch" to "GitHub Actions"!

# AND this file needs to be present in all deployed branches
# as well as the scripts/build-pages.sh script and the line to run it in package.json

name: Deploy to Pages

on:
  # Runs on pushes to these branches
  push:
    branches: # the same list should be used below in the "Build branches" step
      - main
      - deploy
      - control-panel

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    # do not run on forks unless they specify their API key and app ID
    # if: vars.API_KEY != '' && vars.APP_ID != ''
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      HAS_API_KEY: ${{ vars.API_KEY != '' }}
      HAS_APP_ID: ${{ vars.APP_ID != '' }}
      SHOULD_RUN: ${{ env.HAS_API_KEY && env.HAS_APP_ID }}
      SHOULD_RUN2: ${{ vars.API_KEY != '' && vars.APP_ID != '' }}
      SHOULD_RUN3: ${{ vars.API_KEY && vars.APP_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Temp Debug
        run: |
          echo 'env.HAS_API_KEY ${{ env.HAS_API_KEY }}'
          echo 'env.HAS_APP_ID ${{ env.HAS_APP_ID }}'
          echo 'env.SHOULD_RUN ${{ env.SHOULD_RUN }}'
          echo 'env.SHOULD_RUN2 ${{ env.SHOULD_RUN2 }}'
          echo 'env.SHOULD_RUN3 ${{ env.SHOULD_RUN3 }}'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # vars defined in https://github.com/croquet/microverse/settings/variables/actions
      - name: Create apiKey.js
        run: |
          echo 'const apiKey = "${{ vars.API_KEY }}";' > apiKey.js
          echo 'const appId = "${{ vars.APP_ID }}";' >> apiKey.js
          echo 'export default {apiKey, appId};' >> apiKey.js

      # should match the "on push branches" list on top
      - name: Build branches
        run: |
          npm run build-pages \
            main \
            deploy \
            control-panel \

      - name: Upload _site
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
